### PR TITLE
UPDATES!

### PR DESCRIPTION
**Pull request by CUST-0M**
-Adds a reloading bench and forge to the outlaw base. Adds in a pet cat as well cuz why not
-Adds in a new crafting recipe for gaia extract, 6 gaia branches and 50 units of water. Gaia extract is just omnizine but a bit better and doesn't kill you when you overdose.
-Chemistry books sold at the vendor now during hi-pop. Only change I did to vendors.

### CODE REVIEW

**Comment by geemiesif** [comment]
Please dont add a 2nd reloading bench to that area. The kahn side has one you can use without stealing it.

**Comment by CUST-0M** [comment]
The Khans one is for Khans, outlaws can't use it. It isn't too difficult to grab a bench usually but I just thought it'd be better to keep those there for everyone else. Since everything else is fine tho I can update the map some other time.

**Comment by Superballs69** [comment]
Couldn't see what CI was tripping it up, running it again. Please use the template that's given to you when you made the PR as well as resolving the merge conflicts with upstream.

**Comment by MarinaGryphon** [comment]
> Couldn't see what CI was tripping it up, running it again. Please use the template that's given to you when you made the PR as well as resolving the merge conflicts with upstream.

it literally says it on the files changed tab, that's how annotation works

` 	/datum/crafting_recipe/extract_gaia`
there is indentation at the start of this line that shouldn't be there
it turns out if you read things CI makes more sense

**Comment by CUST-0M** [comment]
I made a seperate PR with all the changes but no map a few days ago. This one can be closed.

**Pull request closed without merging**
