### PR TITLE
Followers' Quality of Life Fixes

### PR DESCRIPTION
**Pull request by Tokorizo**
This PR is a recreation of a previous PR that was closed a while ago: https://github.com/DesertRose2/desertrose/pull/471

 all credit goes to **callunaborealis**

Time to make things right again.

## About The Pull Request

**BASEMENT**

- Replace Dorms with simple bedrooms.

- Add glass windows between the kitchen and the new bedroom coridoor.

- Reorganise medical storage, by giving it its own room with organs, bio suits, straight jackets, and prosthetics, locked behind a Follower ID door for security.

- ~~Restores medical research equipment.~~

- Add ore box to mining entrance.

StrongDMM_bWsFDnXncE
StrongDMM_H4KoNOwyGq

**SURFACE**

- Add seed vendor.

- Add a missing light fixture.

- Added shower for easy clean-off or irradiated patients.

StrongDMM_0E2Gk5SKAA

## Why It's Good For The Game

Quality of life improvements for Followers. Less repetitive gameplay for regular Followers players. Better emergent roleplay.

Having the research equipment will allow the faction to pursue one of its lore goals, which is "to gradually shape a better brighter future for the wasteland through education, research, and medical services". As to how the Followers are able to acquire this equipment, in the lore, the Followers are well-equipped back in the NCR so they should have no problem loaning research equipment from better-equipped facilities.

## Changelog
🆑
add: Add shower in surgery room for cleansing irradiated or bloody patients before surgery in the Followers clinic
tweak: changed lights to bulbs for muh underground immersion
add: Add Megaseed Servitor to Followers clinic for QoL
add: Add ore box by mining exit for QoL
add: Add radsuits, biosuits in an old locker for RP with irradiated or infected patients
add: Add straight jackets in the medical store to aid in psychiatry RP
tweak: Medical store is reorganised. Move organ and prosthetic freezers from workshop to medical store and consolidate freezers by type
tweak: Remove snack vendor from Follower Kitchen and just keep it in the main lobby
tweak: Add windows between kitchen and bedrooms coridoor
tweak: Expand and convert dormitory into simple bedrooms
/🆑

### CODE REVIEW

**Comment by K0NFL1QT** [comment]
The Followers base is too pointlessly huge as it is. They shouldn't have RnD, they don't need it. Vault City is coming soon anyway, with an entirely different Followers layout, and they're still not getting RnD because then what's the point of merging them Vault City and _their_ RnD lab?

**Comment by Tokorizo** [comment]
> The Followers base is too pointlessly huge as it is. They shouldn't have RnD, they don't need it. Vault City is coming soon anyway, with an entirely different Followers layout, and they're still not getting RnD because then what's the point of merging them with Vault City and _their_ RnD lab?

Vault City is miles away, it currently is just an idea that hasn't hit live servers, and until it is finished (The map, lore, and the date of release which btw is still TBA), there should be no reason to keep something away for a simple idea that is still a WIP. Also, this RnD is just for medical stuff and only for the Pahrump. Until the day Vault city is done (god knows how long that will take) we can talk about the balance of the Followers and the New Faction, but that faction DOESNT exist currently so that's not a valid argument. Also, the size is pretty perfect currently, RnD removal was the reason why the base is so empty as people hated it, the moment this PR gets merged is when the player base will return to use it. but just because you see one Follower online doesn't mean the faction base is the problem.

**Comment by Ali-nar** [comment]
> > The Followers base is too pointlessly huge as it is. They shouldn't have RnD, they don't need it. Vault City is coming soon anyway, with an entirely different Followers layout, and they're still not getting RnD because then what's the point of merging them with Vault City and _their_ RnD lab?
> 
> Vault City is miles away, it currently is just an idea that hasn't hit live servers, and until it is finished (The map, lore, and the date of release which btw is still TBA), there should be no reason to keep something away for a simple idea that is still a WIP. Also, this RnD is just for medical stuff and only for the Pahrump. Until the day Vault city is done (god knows how long that will take) we can talk about the balance of the Followers and the New Faction, but that faction DOESNT exist currently so that's not a valid argument. Also, the size is pretty perfect currently, RnD removal was the reason why the base is so empty as people hated it, the moment this PR gets merged is when the player base will return to use it. but just because you see one Follower online doesn't mean the faction base is the problem.

Firstly, Vault City isn't miles away, it's hopefully being pushing for mid-late May so not as far away as you think. As in Vault City the Followers will be losing their console and be downsized massively compared to how they are now. The RnD has never been used just for medical purposes, and was decided by devs and Admins to be removed from the Followers due to the Followers abusing it along with the fact that the Followers are a minor faction. The rest of the PR is great, but the research console has to go.

**Comment by Tokorizo** [comment]
> > > The Followers base is too pointlessly huge as it is. They shouldn't have RnD, they don't need it. Vault City is coming soon anyway, with an entirely different Followers layout, and they're still not getting RnD because then what's the point of merging them with Vault City and _their_ RnD lab?
> > 
> > 
> > Vault City is miles away, it currently is just an idea that hasn't hit live servers, and until it is finished (The map, lore, and the date of release which btw is still TBA), there should be no reason to keep something away for a simple idea that is still a WIP. Also, this RnD is just for medical stuff and only for the Pahrump. Until the day Vault city is done (god knows how long that will take) we can talk about the balance of the Followers and the New Faction, but that faction DOESNT exist currently so that's not a valid argument. Also, the size is pretty perfect currently, RnD removal was the reason why the base is so empty as people hated it, the moment this PR gets merged is when the player base will return to use it. but just because you see one Follower online doesn't mean the faction base is the problem.
> 
> Firstly, Vault City isn't miles away, it's hopefully being pushing for mid-late May so not as far away as you think. As in Vault City the Followers will be losing their console and be downsized massively compared to how they are now. The RnD has never been used just for medical purposes, and was decided by devs and Admins to be removed from the Followers due to the Followers abusing it along with the fact that the Followers are a minor faction. The rest of the PR is great, but the research console has to go.

I already commented this in Dev chat, were fine with RnD being removed in the future since will be using Vault City's but until then we don't have an RnD system, and the way it was removed discouraged a lot of active Follower players to go on strike and not play anymore. This is more of a revert until the "vault city" occasion happens (which btw is weeks) , also I've had this discussion in Dev chat already if an individual is abusing the RnD system, (Making grenades, napalm, whatever immoral shit) they should be bwoinked for LRP for not acting like a Follower, the punishment of an entire group is not a legit reason to outright remove it, it's not a good way to handle a faction, nor is it fair toward the players who used the RnD respectfully and obediently.

**Comment by K0NFL1QT** [comment]
The Followers got on fine without it all this time. The Followers are doctors first and foremost, and while they dabble in science and research (mostly sociology, psychology and yes robotics), they've not shown the capacity to _make_  any of the implants they sell in NV. In fact it's stated they scavenge for these implants and much of their supplies.

The Followers shouldn't be mining, they're doctors. They shouldn't have RnD. Their clinic should be a _lot_ smaller and much more run down, if they should have one at all. They're supposed to be underfunded, under equipped wasteland doctors getting by with whatever supplies they can scrape together.

At this point we have two factions with RnD, the server doesn't need a third. One is surface accessable, and has a tight control on it, The other is about to _become_ surface accessable. _The main town of the server is about to be selling RnD tech_. The Followers are altruists, they're not going to have a tight control of it. They're going to be giving away, or selling, parts and circuits. Everyone will have dna manipulators, or protolathes for grenades, or personal sleepers because 'lol bought it from the Followers', thus ruining the low tech wasteland aesthetic. You don't need it to make chems, or do surgeries, and it will get removed with Vault City anyway and we'll have to deal with this childish strike all over again because 'well you had it back for a few weeks'.

**Pull request closed without merging**
