### PR TITLE
Supermutant DMI update

### PR DESCRIPTION
**Pull request by DrAtomix**
## About The Pull Request

A simple addition to the Supermutant DMI file that introduces three new sprites of Supermutants in legionary gear and armor. They look good in my opinion and can be used for events or other things later on for people working on the game. It's just a basic sprite addition adding the artwork for later use by people. 

Includes three new versions of a super mutant:
A Supermutant in basic legionary fatigues.
A Supermutant in legionary fatigues and some armor.
A Supermutant in legionary fatigues and Centurion Armor.

And it also adds their dead state to the Dead_Supermutant DMI

## Why It's Good For The Game

I believe that adding additional artwork and mobs to the game doesn't hurt. The intent for which I add these are to expand options and possibly have a couple of events for legion or other factors utilizing this artwork. I believe they look good- particularly the one with Centurion armor /looks/ badass. If nothing else, having these as a basis in the DMI can be used later down the road by other artists or spark ideas for people, and would like to make my artwork available for use by others.

## Changelog
:cl:
imageadd: Legionary Supermutant, Armored Legionary Supermutant, Centurion Supermutant icons. 
imageadd: Dead states for all the aforementioned icons.

/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
It took me a moment to realize that these were complete submissions for simple-mobs and not misplaced sprite models. 🤭

Look very good, some of the armed roles with asymmetrical features however (nightkin particularly) lack a basic unarmed sprite of each variation, which a spriter later down the road looking at porting the costumes as their own individual clothing attachments might want to use by removing the mutant from the frame so it slots on properly to a player-supermutant.

**Comment by DrAtomix** [comment]
I have no idea about those in particular, I'll be perfectly honest- I'm very unfamiliar with Github. The only things that should be changed in this particular PR is the addition of those 3 sprites in the Supermutant DMI- anything else would be unintentional(which I'm not too sure how this could occur) or something that was existent and unrelated to the additional sprites added. I do agree however, that the clothing added in the ones I did should be looked at making an additional version with the mutant removed from the frame for player usage later on. The armor is cool and could be neat in-game.

Mostly, I just wanted them as Mobs for use in events.

**Comment by FantasticFwoosh** [comment]
You can continue adding commits to a open PR branch if you'd like to remove them, once the commit goes through, this PR space here updates the changes in real time. (extending until the pr is merged, then a change would require a new PR)

**Comment by judgex** [comment]
Is this ready for merge?

**Comment by DrAtomix** [comment]
> Is this ready for merge?

Yep should be! Noticed the dead state thing too, and added those quickly to the PR.

**Pull request merged**
