### PR TITLE
Doublestacked deagle and few NCR changes

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request

Adds extended version of the desert eagle magazine and makes it tad bit cheaper (seriously why does it cost wood when it has zero wooden parts)
Makes it so army and rangers both use their respective bandoliers with the army one being turned around to not cover the mantle
New NCR facewrap icon and updated colors
Removes the stupid amount of IFAKs from medical officer and just gives them to him in a medkit

## Why It's Good For The Game

Desert Eagle for a long time was underused weapon after it's numerous nerfs back when it was still .50AE, it having extended magazine should help it be more viable in comparison to revolver
Army and Rangers always had a seperate bandolier but certain loadouts didn't reflect that also the facewrap still was still its BD version
MO spawning with 3 IFAKs instead of just having a medkit is dumb

## Changelog
:cl:
add: extended desert eagle magazines
tweak: ncr bandoliers and facewrap
fix: weirdness of MO loadout
/:cl:

### CODE REVIEW

**Comment by buffyuwu** [comment]
waiting on balance team

**Comment by SouthyOsmanli** [comment]
there's only 2 active members of the balance team anymore; myrios and i. we both stated we didn't mind it to lama

**Comment by buffyuwu** [comment]
> there's only 2 active members of the balance team anymore; myrios and i. we both stated we didn't mind it to lama
> 
> i was never reached out to

yea i posted it in the balance channel thinking there was a whole team still lol

anyway

**Comment by buffyuwu** [comment]
code/game/objects/items/storage/firstaid.dm, line 59, column 2:
error: failed to resolve path /obj/item/reagent_containers/hypospray/medipen/stimpak

linters missed this, but a simple fix. feel free to re-open a new one when you've fixed it

**Pull request merged**
