### PR TITLE
(Project) Porting New Armor System & Penetration System Changes

### PR DESCRIPTION
**Pull request by SouthyOsmanli**
## About The Pull Request

**This currently is a work in progress.** I will specify when this is good to merge; doing this partially so I can get feedback on what should be removed/isn't needed, armor value changes and feedback from the balance team and coders.

In short, this PR aims to do away with our linearmor system. The system isn't 'bad' but the tier system with how our current armor pentation works is a bit.. wonky. This PR would switch us over to a threshold system instead of a simulated health which _should_ benefit out combat system more.

- Threshold system based off Eris' simple system.
- New defines to allow for armors to have different insulations, features and so forth which should make armors feel more 'unique'.
- Porting a armor penetration system akin to what Eris has. Eris has multiple ammo types and is a server where I feel their ammo types are relatively well balanced between rubbers, hollow points (which some guns have), FMJ/default rounds, high velocity rounds (Basically AP), and some other specialty rounds.
- Ammo damages and penetrations adjusted to this new system of armor and penetration.

Currently **this is a framework**. I will be busy so this is going up for coders like Raptor or balance team members like Myrios to go over and get a list of what they think armor values should be set to, what armors can be trimmed due to being unnecessary/outdated and, if anyone wishes to, continue the project while I'm busy for a week.

## Why It's Good For The Game

I'll put something serious this time around in this section.

Overall, the ammo system we have is good but certain arounds such as what Match did and AP have had issues of being the 'meta' round and a constant armor tier creep that has not been inherently beneficial. Armor tiers 1-3 are near worthless while certain armors, like tier 5+, is just better to use AP against due to penetration just acting akin to a damage multiplier rather than truly feeling like it's 'bypassing' armor.

Eris may have flaws with some of its systems but its gunplay and armor is strongpoints. So I'm attempting to port **some** of these features over that fit. Specifically the following:
- Armor threshold system.
- Armor pentation system.
- Extra defines for easy-to-do organization (hopefully).
- And some misc features such as insulation in armors which may come in handy for events or snow maps if mechanics are wanted for temperatures again.

## Changelog
:cl:
add: New armor threshold system based off Eris' base system.
balance: Rebalances armors to new values based on the new system.
/:cl:

### CODE REVIEW

**Comment by buffyuwu** [comment]
yeah please don't

the 0xnumber changes are unneeded especially

eris isn't in a great state as a repo and has virtually no code quality checks because of how broken the base is. i heavily discourage anything being directly based on eris code let alone redefining core macros

**Comment by buffyuwu** [comment]
another worthy mention if you're directly copying code from another place please please please cite the PR on said place where that code was added initially so we can cross reference

**Comment by SouthyOsmanli** [comment]
image
> eris isn't in a great state as a repo and has virtually no code quality checks because of how broken the base is. i heavily discourage anything being directly based on eris code let alone redefining core macros

feel free to do a port yourself. i put this up as a draft to show lama and raptor what i was aiming towards.

**Comment by buffyuwu** [comment]
>feel free to do a port yourself since you keep contradicting yourself with what you've even told me. **i put this up as a draft** to show lama and raptor what i was aiming towards and to have help on it but - haven’t gotten any.

i don't see the purpose in this hostility. i'm not contradicting myself by examining the eris base after that point and making a determination that the codebase is troublesome. not only that, the work you have presented here was a **pull request**, not a draft as you suggested. you could've easily worked on this as a draft before opening a PR here, or marked it clearly as a draft with the 'convert to draft' button as i had.

people often open/close/convert-to-draft/convert-to-pr etc so your OP mentioning it being a WIP doesn't help me in this case

>doing this partially so I can get feedback

on the first line of the PR, you are asking for feedback. i am giving you feedback. please don't get upset that you receive feedback that you do not like.

i haven't seen any progress in nearly 12 days now, so i'll go ahead and close this for you

**Comment by SouthyOsmanli** [comment]
considering i told everyone that i was going to be on vacation, and just returned yesterday, yeah, i haven't done much work.

thank you for closing it i guess without - even just asking first when ive been asking lama to take a look for a day or two now.

**Comment by MarinaGryphon** [comment]
> image
> 
> > eris isn't in a great state as a repo and has virtually no code quality checks because of how broken the base is. i heavily discourage anything being directly based on eris code let alone redefining core macros
> 
> feel free to do a port yourself since you keep contradicting yourself with what you've even told me. i put this up as a draft to show lama and raptor what i was aiming towards and to have help on it but - haven’t gotten any.

"*If* they have good code, port it" and "This is not good code, don't port it" aren't contradictory, the latter literally follows from the former.
Let A(x) be the predicate "X is good code."
Let B(x) be the proposition "You should port X."
Buffy said `A(Eris combat code)<->B(Eris combat code)`, aka "If and only if Eris combat code is good code, then you should port Eris combat code."
Buffy also said `~A(Eris combat code); ~A(Eris combat code)->~B(Eris combat code); therefore ~B(Eris combat code)`, aka "Eris combat code is bad code. If Eris combat code is bad code, you should not port Eris combat code. Therefore, you should not port Eris combat code."
By the definition of the biconditional, `A(Eris combat code)<->B(Eris combat code)` also means that `B(Eris combat code)->A(Eris combat code)`.
By the law of contraposition, we can then say that `~A(Eris combat code)->~B(Eris combat code)` follows from `A(Eris combat code)<->B(Eris combat code)`.
If we take `~A(Eris combat code)` to be true, then Buffy's claim that `~B(Eris combat code)` is also true is true, following from the original statement Buffy said in the screenshot.
Therefore, what Buffy said was not a contradiction.

**Comment by SouthyOsmanli** [comment]
image
it was in fact contradictory since this was directly asked to both of you. and this was an attempt at a direct port of the armor code.

**Comment by MarinaGryphon** [comment]
"if you can do it, and test it, and make sure it passes CI, then sure. if not, it's a bad idea" is literally exactly what I said both here and there

**Comment by SouthyOsmanli** [comment]
im - literally not even done getting the code done, yet it was closed after i stated to others i am going on vacation for a week and gave myrios (who told corvo and tef), raptor and other coders the first thing im doing upon coming back was going through and working on this.

im rather done arguing this, i'll just open another pr and get back to working on it.

**Comment by buffyuwu** [comment]
> im - literally not even done getting the code done, yet it was closed after i stated to others i am going on vacation for a week and gave myrios (who told corvo and tef), raptor and other coders the first thing im doing upon coming back was going through and working on this.
> 
> im rather done arguing this, i'll just open another pr and get back to working on it.

we ideally don't want to let PRs/drafts sit for 12 days with no progress. of course you're free to have your early-stages project on your account's fork of DR2 where you originally opened the pull request from.

the reason for this is primarily that you're touching 15 files, among them important ones, and anyone looking to submit code for review might see you're touching files they're touching and decide against it, waiting for your project to be merged. just about any new item/weapon/armor/etc project would be cautioned by the presence of a PR like this.

**Pull request closed without merging**
