### PR TITLE
CASP tweaks and buffs and nerfs

### PR DESCRIPTION
**Pull request by Stalkeros2**
## About The Pull Request
First of all, made pouches CRAFTABLE, which is really-really cool.
Combat shotguns were replaced with Neosteads and WTs with 10mms, as well as 5.56 ARs, because I could.
Replaced most, if not all available tackle gloves with normal combat gloves.

## Why It's Good For The Game
~I honestly have no idea but why not lmao.~
Fixed WTs not working, as well as expanded Vault's trading/defense potential and... muh Vault bias lmao.

## Changelog
:cl: Stalkeros
add: More weaponry to the Vault's CASP.
add: Craftable leather pouches when? Craftable leather pouches **now**.
del: Removed WTs, now replaced with 10mm SMGs.
balance: SWAT armor = T-45 now.
/:cl:

### CODE REVIEW

**Comment by AsterixCodix** [comment]
I would've appreciated some level of communication on this, but considering how Cog City won't have the CASP system, at least initially, I don't see much point in these changes as they won't affect all that much in the long term.

**Comment by Stalkeros2** [comment]
oh

**Comment by Dioclex** [comment]
Furthermore, I see little need in giving the Vault even more high-tier items and more of an arsenal. At it's current stage it's pretty extreme, but giving them T45 is absolutely obscene. That is not balance, that is lunacy.

**Comment by Stalkeros2** [comment]
Right.

**Pull request closed without merging**
