### PR TITLE
Fixes BoS knights not having gunsmith traits

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Currently, BoS Knights, Sr. Knights and Knight Cpts don't receive gunsmith training upon spawn and must read (destroy) a gunsmithing book to learn gunsmith by lore they should already know. This gives all fully fledged knight castes the knowledge of the GnB recipes at roundstart.

Note: this doesn't actually give Knights GnB 'traits', so if anyone changed the recipes of what GnB manuals taught that wouldn't be reflected here.

## Why It's Good For The Game

Currently the GnB books don't give traits and I don't know how to make them properly give traits without messing anything up. So this is a band aid fix to a fairly annoying gameplay issue.

## Changelog
:cl:
tweak: The BoS knight caste can actually do gunsmithing as their flavour description suggests.
balance: BoS Knight castes no longer start with a tier 3 gunbook; initiates start with a tier 1 and 2 gunbook (they're students so they're still studying I guess?)
/:cl:

### CODE REVIEW

**Comment by buffyuwu** [comment]
>Currently the GnB books don't give traits and **I don't know how to make them properly give traits without messing anything up**. So this is a band aid fix to a fairly annoying gameplay issue.

the easiest way to add a trait would be in the init, just run ADD_TRAIT() with the arguments you want

**Comment by githubuser4141** [comment]
> > Currently the GnB books don't give traits and **I don't know how to make them properly give traits without messing anything up**. So this is a band aid fix to a fairly annoying gameplay issue.
> 
> the easiest way to add a trait would be in the init, just run ADD_TRAIT() with the arguments you want

Would adding extra gunsmith traits mess with anything? I thought about doing this earlier but didn't know how this would correspond to gaining the recipes. What's the best way of making "gunsmith_one" == knowing the recipes of the gunsmith one crafting recipe giver?

**Comment by buffyuwu** [comment]
> > > Currently the GnB books don't give traits and **I don't know how to make them properly give traits without messing anything up**. So this is a band aid fix to a fairly annoying gameplay issue.
> > 
> > 
> > the easiest way to add a trait would be in the init, just run ADD_TRAIT() with the arguments you want
> 
> Would adding extra gunsmith traits mess with anything? I thought about doing this earlier but didn't know how this would correspond to gaining the recipes. What's the best way of making "gunsmith_one" == knowing the recipes of the gunsmith one crafting recipe giver?

gunsmith_one (on lonestar at least lol) for example is:
```
/obj/item/book/granter/crafting_recipe/gunsmith_one
	name = "Guns and Bullets, Part 1"
	desc = "A rare issue of Guns and Bullets detailing the basic manufacture of firearms, allowing the reader to craft firearms. It's barely holding up, and looks like only one person can study the knowledge from it."
	icon_state = "gab1"
	oneuse = TRUE
	remarks = list("Always keep your gun well lubricated...", "Keep your barrel free of grime...", "Perfect fitment is the key to a good firearm...", "Maintain a proper trigger pull length...", "Keep your sights zeroed to proper range...")
	crafting_recipe_types = list(/datum/crafting_recipe/ninemil, /datum/crafting_recipe/huntingrifle)
```
specifically we can see it teaches list(/datum/crafting_recipe/ninemil, /datum/crafting_recipe/huntingrifle)

so for our gunsmith traits, we'd take the crafting_recipe_types that this granter gives (and the other levels) and add them to a gunsmith trait datum, then run ADD_TRAIT() for when we're equipping our knights when they spawn and add them that way.

:)

**Comment by buffyuwu** [comment]
BUT this method seems standard on fo13; the method of teaching the crafting recipe outside of a trait.,., the only trouble is you end up repeating this teaching code all across the base when you could just put it in a trait, and let that trait be added where it needs to be.

the benefit of a clean codebase makes it easier to read and also for newer devs to contribute and understand :D

**Review by buffyuwu — APPROVED** [review]
normally i don't approve bandaid fixes but this is fine

**Comment by SingingSpock** [comment]
Firstly, Knights not having gunsmithing traits is deliberate; Sword Scribes are now the main gun manufacturers of the chapter. Knights do get GnB 3 in their bag so they can make attachments. Secondly, any change to the balance of a faction like this needs to go through the balance team before it is put up as a PR for final approval. Thirdly, on a QoL level, I highly doubt Knight players actually *want* a bunch of shit guns clogging up their crafting menu, there is nothing actually worth making in that whole list other than the attachments they already get with GnB 3.

**Comment by judgex** [comment]
So, is this to be merged, does it need more work?  More discussion?

**Comment by SingingSpock** [comment]
I can say it was not discussed by the Brotherhood lore team, nor do I see discussion of it in the balance channel of the coding discord. It hasn't been approved by any of the people it should be approved by, so it shouldn't be merged.

**Comment by githubuser4141** [comment]
> Firstly, Knights not having gunsmithing traits is deliberate; Sword Scribes are now the main gun manufacturers of the chapter. Knights do get GnB 3 in their bag so they can make attachments. Secondly, any change to the balance of a faction like this needs to go through the balance team before it is put up as a PR for final approval. Thirdly, on a QoL level, I highly doubt Knight players actually _want_ a bunch of shit guns clogging up their crafting menu, there is nothing actually worth making in that whole list other than the attachments they already get with GnB 3.

Oh, well. I was not aware of the sword scribes being the chapter's gunsmith and thought it was a bug/oversight with how someone gave the knight caste all four tiers of "gunsmith_X" without it doing anything. Also.. someone in the LS discord found it odd how DR2 _initiate knights_ start with a tier 2 gunsmith book when fully fledged knights don't. Fortuna/LS [fixed it](https://github.com/FortunaSS13/Fortuna/pull/389) by giving knights a tier1/2 gun book at spawn THOUGH I suppose this could be important if their bunker didn't spawn with gunbooks already. Anyway yeah I'll probably close this in a bit

**Pull request closed without merging**
