### PR TITLE
Unnerfs AER14 and Wattz 2000

### PR DESCRIPTION
**Pull request by Knightfall5**
## About The Pull Request
Makes the AER 14 and Wattz 2000 better than the common AEP 7 laser pistol.

## Why It's Good For The Game
Rare guns should be better than less rare guns. Seriously, over twice the fire delay of an AER 9 and four times an AEP 7? These guns were only slightly better than the much more common laser variants to begin with and needed no nerfs at all, let alone the complete gutting they received.

## Changelog
:cl:
balance: reverts the nerf to the AER 14 and Wattz 2000
/:cl:

### CODE REVIEW

**Comment by panzer1944** [comment]
Uuhhh the PR i just did reverts it back to 4.5, which is how it was and how the AER9 fires.
You're not reverting it like my PR is, you're buffing it.

**Comment by Knightfall5** [comment]
The original value was 3.5, which you can easily check here https://github.com/DesertRose2/desertrose/pull/393/commits/901f6364e61ffb8f115e15b8e98d81f39d0721bb 

If you were to actually revert it to the original value there would indeed be no reason for this PR.

**Comment by panzer1944** [comment]
> The original value was 3.5, which you can easily check here [901f636](https://github.com/DesertRose2/desertrose/commit/901f6364e61ffb8f115e15b8e98d81f39d0721bb)
> 
> If you were to actually revert it to the original value there would indeed be no reason for this PR.

As I said in the discord conversation, the ability to ping me to fix the minor error of me believing the original FD value to be 4.5 existed, and by consequence there is no reason for this PR, especially when I've stated I'll edit it to 3.5 in my existing PR when my internet stops shitting itself. By consequence, I'm still requesting you close this PR as to prevent any conflicts if they both get merged at the same time - which mind you probably won't happen today.

**Comment by Knightfall5** [comment]
I didn't know a PR to revert said changes even existed when I made this PR, which makes pinging someone about it kind of hard. But yes, this revert has no further need to exist so I'll close it

**Pull request closed without merging**
