### PR TITLE
Big Horners fix

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request

Fixes the issue with bighorners hitting eachother randomly
#37 

## Why It's Good For The Game

Makes big horners not attack eachother thats about it.

## Changelog
:cl:
fix: Fixed bighorners attacking eachother
/:cl:

### CODE REVIEW

**Comment by Risquu** [comment]
This won't fix the issue.

The cause is that Big Horners have the var `attack_same = 1`. One potential fix is to set their faction to bighorner only and set `attack_same = 0`, however the reason I've not PRed that myself is because that means when a big horner agroes onto someone, all the other big horners around would do so too even if they don't "have an evil glint in their eye" - It may still be a suitable fix.

**Review by MarinaGryphon — CHANGES_REQUESTED** [review]
> This won't fix the issue.
> 
> The cause is that Big Horners have the var `attack_same = 1`. One potential fix is to set their faction to bighorner only and set `attack_same = 0`, however the reason I've not PRed that myself is because that means when a big horner agroes onto someone, all the other big horners around would do so too even if they don't "have an evil glint in their eye" - It may still be a suitable fix as that would be a more minor issue than the current issue.

The solution then would be to either:

1) Make surrounding big horners give the evil glint message when a big horner triggers the call for backup proc.
2) Stop big horners from calling for backup.

As it stands, this PR would not work.

**Comment by Lamasmaster** [comment]
Commited the requested changes however I noticed there still seems to be an issue of big horners sometimes still attacking you if you stand close to another one, however that doesn't when attacked from ranger or when you walk away fast enough from melee.

**Comment by Risquu** [comment]
I think that new fix is fine given no other fixes have been put forward, it's not perfect but it's better than the existing bug. It's not a sufficiently major issue to be chasing perfection with it.

**Comment by MarinaGryphon** [comment]
> The solution then would be to either:
> 
> 1. Make surrounding big horners give the evil glint message when a big horner triggers the call for backup proc.
> 2. Stop big horners from calling for backup.
> 
> As it stands, this PR would not work.

This hasn't been addressed.

**Pull request closed without merging**
