### PR TITLE
BoSBunker Patch

### PR DESCRIPTION
**Pull request by K0NFL1QT**
Hotfix for #462

Fixes;
Airless Codex tiles
Missing Initiate spawns
Make reactor ~~safer/larger~~ smaller, do not inject higher than setting 2 but this still output over 8x more power than is needed - https://i.imgur.com/IWGGd8r.png
Give Proctors bookshelves that aren't empty
Removes the starter mirelurks to prevent an early horde
Fixes orientation of prisoner cell - https://i.imgur.com/Hzu8JtS.png
Reoriented the medical apc so it's actually connected.

### CODE REVIEW

**Comment by geemiesif** [comment]
what do you mean reactor safer/larger ?

**Comment by K0NFL1QT** [comment]
> 
> 
> what do you mean reactor safer/larger ?
Given the way the AM Reactor works, I sized it too small. The current size only creates 2 cores, and thus explodes if you set it over injection rate 3. I've increased it slightly so there's space for 3 cores, making you able to go up to injection 5 without exploding it. Which is still less than the previous 4 cores/7injection limit.

**Comment by geemiesif** [comment]
> > what do you mean reactor safer/larger ?
> 
> Given the way the AM Reactor works, I sized it too small. The current size only creates 2 cores, and thus explodes if you set it over injection rate 3. I've increased it slightly so there's space for 3 cores, making you able to go up to injection 5 without exploding it. Which is still less than the previous 4 cores/7injection limit.

Well I dont see why we need to expand it , is it not making enough power? I ask this for  we are trying to downsize things not grow them , also if you are making map changes please post screenshots of the areas you resize.

**Comment by K0NFL1QT** [comment]
> Well I dont see why we need to expand it , is it not making enough power? I ask this for we are trying to downsize things not grow them , also if you are making map changes please post screenshots of the areas you resize.

Unsure on if it's making enough power in its current state as I don't know a way to check its draw without certain consoles, but I believe even at max this version is barely enough to cover the SMES units. Granted we can reduce the number of SMES, but I need a way to find out the bunkers actual draw first. This three core setup is still smaller than the last four core setup.
https://i.imgur.com/GZ1ImKx.png

**Comment by K0NFL1QT** [comment]
The difference between two cores and three cores is huge, given that I think power output in the AM reactor doubles per unit of injection if you have the cores to process it without instability. Basically two cores seemed dangerously slim to the margin, while three cores lets us set the engine comfortably at 4 or 5, which is enough to run the bunker and any reasonable additions.

**Comment by geemiesif** [comment]
> The difference between two cores and three cores is huge, given that I think power output in the AM reactor doubles per unit of injection if you have the cores to process it without instability. Basically two cores seemed dangerously slim to the margin, while three cores lets us set the engine comfortably at 4 or 5, which is enough to run the bunker and any reasonable additions.

 I just want to point out that the vault runs all it does including research/robotics/medbay etc off one core.  I sent it off to the BOS lms to approve this or not.

**Comment by K0NFL1QT** [comment]
I'm happy to reduce it overall once I can figure out the bunkers draw. But you're right, it is mostly just a bunch of lights in the BoS. Even 200k output _should_ cover it, but I'd rather reduce it in stages than go too far at once and make the bunker not generate enough power.

**Pull request merged**
