### PR TITLE
Replacing the secdrobes with clothing racks

### PR DESCRIPTION
**Pull request by Metriusthehot**
## About The Pull Request

The dumb stupid and dumb sec drobes with all the faction clothes are gone, I replaced them with a simple clothing rack sprite and the clothes on top. 
(The clothing racks are just resprited racks so you can click to place on them)

## Why It's Good For The Game

Secdrobes ruin my IMMERSION.

## Changelog
:cl:
add: clothing rack sprite
del: sec drobe
/:cl:

### CODE REVIEW

**Comment by CrowbarLamb** [comment]
yeah but i like the secdrobes they're cool

**Comment by companoo** [comment]
ideally if making sprite PR put the sprite in the PR

**Comment by Metriusthehot** [comment]
Added more things making this pretty much another pr in and of itself.

All are general map fixes except the balance fixes to the vault bunker. Pretty much, I put more medical supplies in the medbay area, slightly lowered OVERseer's speed (it was at 3x now its at2x) and I took off the unstoppable flag. So he can't shoot through walls aaand you actually have a CHANCE of flanking. He still has sporadic movements and can break all the walls. This will hopefully make people actually do that bunker because tbh no one does it and if its completely unused we shouldnt have so many mobs in there. 

Also every single sideways bench on the map was non existent so I added those in, legion looks like an actual stadium now, cog diner has booths, etc. 

cl/
add: blue booth sprites
fix: booths and chairs
balance: vault bunker
/cl

**Comment by Metriusthehot** [comment]
I undid the overseer thing you can meeeerge it now

**Pull request merged**
