### PR TITLE
Disabling of Pax, Salve and Choral Hydrate

### PR DESCRIPTION
**Pull request by SouthyOsmanli**
## About The Pull Request

Due to issues relating to players using these chems, either due to making no sense, being unbalanced or 'powergamed'/unfair use in combat I've disabled the three aforementioned chems.

## Why It's Good For The Game

**Pax** is unbalanced and has been banned by admins from any sort of use because, and I quote, 'it's stupid'. Pax leaves no chance for others to fight back due to forcing everyone to be passive who inhales it. If the chem is banned from use, it should simply be disabled in the code to prevent its use in the first place.

**Salve** is a bit silly to have and can work as a lesser-stimpac with no overdose threshold. Since no one has wanted to fix the chem it's probably easier to remove it to avoid it being powergamed. I myself have cheesed a lot with this chem as factions, like the Brotherhood, can mitigate the chem's only side effect by using a health hud (chem stops you from seeing how damaged you are). This is _not_ me complaining about the Brotherhood or the like since.. I mean, I play BoS and cheesed this a lot in the past. Probably shouldn't be a thing and I cannot figure out a better way to rebalance it since it makes other chems obsolete sometimes.

**Choral Hydrate** has been back and forth in admin rulings for awhile. It's banned from being used in combat but appears to have no use besides 'funny sleepy regent' used in rapid syringe guns or dart guns outside of the use in grenades. This chem is typically banned in knockout gas grenades and banned as well if used against fighting players in syringe form due to being used in a gun. Other chems do the same job as Choral but are less pottant or take longer to take effect (ex morphine or zombie powder). So why have it at all???

**NOTE:** I have kept all of these still in-code but just disabled them. If someone wishes to use these in the future they will still be in the code for use. Only code touched otherwise is changing toxin-cookies from.. choral to cyanide. Which I do not believe will effect the game majorly anyway?

## Changelog
:cl:
del: Disables Pax, Choral Hydrate and Miners Salve (both craftable versions) in-code.
/:cl:

### CODE REVIEW

**Comment by judgex** [comment]
Not sure why this is failing checks.  If you can resolve it, ping or DM me and I will move this along.

**Comment by SouthyOsmanli** [comment]
Can't figure out why as when I run my own server it compiles, starts and acts as normal. Seems to work as intended in tests. 

No clue what is causing any conflicts.

**Comment by Lamasmaster** [comment]
You left space in these two somewhere, which causes it to error.

code/modules/reagents/chemistry/reagents/toxin_reagents.dm: /* /datum/reagent/toxin/chloralhydrate

Imagine its refering to the comments.
// new > //new
/* /obj/item/reagent_containers/syringe/lethal/choral

**Comment by Superspheres** [comment]
> 
> 
> You left space in these two somewhere, which causes it to error.
> 
> code/modules/reagents/chemistry/reagents/toxin_reagents.dm: /* /datum/reagent/toxin/chloralhydrate
> 
> Imagine its refering to the comments.
> // new > //new
> /* /obj/item/reagent_containers/syringe/lethal/choral

Just also good to get in the habit of using indentations instead of using spacebar for code, so this wont trip up CI again.

**Comment by SouthyOsmanli** [comment]
Even upon fixing that still seems to fail checks.

**Comment by SouthyOsmanli** [comment]
There, should finally work in full after fixing all the errors. Strange to me that gave such a problem. 

In testing appears to work as intended. Can switch stuff around if needed in regards to sleepy-pen or.. the cyanide cookie (But I kind of find that funny.)

**Pull request merged**
