### PR TITLE
Myrios' Change PR

### PR DESCRIPTION
**Pull request by SouthyOsmanli**
## About The Pull Request

As requested by Myrios, he wished for me to re-enable Enclave for the highest level RP he had seen. The Enclave. The best faction ever. Myrios LOVES the Enclave, he told me so.

## Why It's Good For The Game

Enclave here.
My video feed is working.

## Changelog
:cl:
adds: enclave enclave enclave myrios asked for this 100%
/:cl:

### CODE REVIEW

**Comment by Myrios** [comment]
DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED DENIED

**Comment by panzer1944** [comment]
Fuckyoufuckyoufuckyoufuckyoufuckyoufuckyoufuckyouhatred

**Comment by Tokorizo** [comment]
cope and seethe

**Comment by AsterixCodix** [comment]
Needed a good laugh this week, and this was better than a lot of stand-up

**Comment by SouthyOsmanli** [comment]
image

**Comment by SouthyOsmanli** [comment]
**You (cough), you haven't won here. You and your mutie-bastard friends are gonna join me in a big ol' mushroom cloud sendoff. I just triggered the self-destruct. (Heh, heh; cough, cough,...) The work will go on. You didn't do nothing here, 'cept seal your own death warrants. Duty, (cough) honor... courage... Semper Fiiiii.......**

**Pull request closed without merging**
