### PR TITLE
armor, ammo, etc

### PR DESCRIPTION
**Pull request by nokele**
Made ammo require compressed blackpowder, made by using 1 cloth and 50 blackpowder, removed blackpowder from vending machines. Idea is more scarcity of ammo.

Buffed armor by like 20-30% across tiers.

### CODE REVIEW

**Comment by Risquu** [comment]
Doing tier values for wound won't really work well like that. I'm guessing wound armour is a percentage chance to prevent a wound? I wouldn't try to use the linearmor system for it. I would do it one of two ways (tier list numbers are ass pulled, consider using your own):
```
var/tierwound = list(10, 20, 30, 40, 50, 55, 60, 65, 70, 75, 80)

...

	if(tier) //ASSIGNS ARMOR VALUES BASED ON TIER, IT WILL USE ARMOR VALUES INSTEAD OF THE TIER FOR THAT VALUE IF THE ARMOR VALUE IS PRESENT
		linemelee = linemelee+tierline[tier] //If an armor has a tier value, having a linemelee value will add onto that tier value rather than replace it.
		linebullet = linebullet+tierline[tier]
		linelaser = linelaser+tierline[tier]
		wound = wound+tierwound[tier]

```
OR

```
	if(!wound)
		wound = tierwound[tier]
```

This depends whether you want wound values on armor's armor list to add onto the tier wound armor (or subtract if negative) or overwrite the tier wound armor.

If going for the former, make sure you review all existing armor lists that have a wound armor set and balance accordingly.


Otherwise: I'd knock tier 1 linearmor down to 20. Tier 1 is like, basic clothing - i.e. wearing a jumper, it'll do a little bit to stop an axe blow compared to wearing nothing, but it's not going to be noticeable and you're still going to have an axe wound.



And seeing as people are paying a lot of attention to armor, I figure I should outline a bit of what my plans were (which I might get back to, I might not): 1) Expanding the armor plating system - currently used on raider armor - to add it to most armors and having different craftable kits required (and perhaps breaking these down into melee, bullet and laser, so to fully upgrade your armor you need to craft one kit of each).
2) Adapting the code for uniform accessories to have helmet and suit accessories (code is in there in rudimentary form for suit accessories but it needs work), that can give bonuses to one or two stats in exchange for penalties in others.
Main point of linearmor was to make adding armor bonuses onto armor balanced, so those two mechanics would use that.

Also one thing I haven't managed to solve with linearmor was making armor from different sources (e.g. uniform and suit, or physiological armor and suit armor) add together as linearmor (they do add together for attachments and plating though), they currently add the % damage reduction together, which is how it was before the overhaul. The relevant code for this is in human_defense.dm

**Comment by Risquu** [comment]
Ehhh I'd still suggest making a separate tier list with tier values for wound in addition to tierline instead of basing off of tierline, as while that may be functional to divide tierline by 3, it means wound values cannot be balanced independently from linearmor values. Also armors with wound values already will need changing - I think it's mainly just power armor that has these.

Also var/linewound can be deleted.

**Comment by nokele** [comment]
Ye, I'm just mainly being lazy and seeing what works.

**Comment by Risquu** [comment]
`wound = wound+(tier*10)` is also a bad idea if wound armour is percentage chance of avoiding a wound (which I'm just assuming it is). As if percentage damage reduction, with percentage chance to avoid something, going from, for example, 90 to 100% is far more significant than going from 0 to 10% so I would advise there to be a diminishing increase with each tier. Also with *10, that means tiers 10 and 11 may have complete immunity (unless it's capped at 90% like, for example, melee armour. Just do `var/tierwound = list(` and `wound = wound+tierwound[tier]` aaaaaaahhhhhh

Also `var/tierline = list(50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550)` lmao what. Converted to % damage reduction those values would be: 33.3, 50, 60, 66.6, 71, 75, 77, 80, 81.8, 83.3, 84.6. If people are made out of paper to the extent that those values are warranted then we need to be nerfing bullets instead, hopefully you're still just trying things.

**Comment by Risquu** [comment]
>If people are made out of paper to the extent that those values are warranted then we need to be nerfing bullets instead

Actually, having said that, just nerf bullets anyway lmao. While someone going down after being shot thrice may be realistic, it's not very fun.

**Pull request merged**
