### PR TITLE
NCR POW Medal + Tina Ranger Gear (Sprites!!!)

### PR DESCRIPTION
**Pull request by pisshole**
The original attempt at sending this through got skipped over; it had to be redone, but I mistakenly sent a version with only the code and none of the sprites. This adds those sprites.

## Why It's Good For The Game
Fixes the NCR POW medal to have its sprites. Additionally adds my character's own ranger gear's sprites.

## Changelog
:cl:
Adding lost sprites to code
/:cl:

### CODE REVIEW

**Comment by pisshole** [comment]
How can this be fixed? please help

**Comment by pisshole** [comment]
THis is the second time I've tried to get these in the game, please help me

**Comment by pisshole** [comment]
I had to remove part of the PR. again. I want to make it clear I literally have offered to pay people to put this in for me and have been pretty much refused. I'm really frustrated I'm going to have to PR this a third time after to finally get the Jacket in

**Comment by BurpleBineapple** [comment]
> I had to remove part of the PR. again. I want to make it clear I literally have offered to pay people to put this in for me and have been pretty much refused. I'm really frustrated I'm going to have to PR this a third time after to finally get the Jacket in

Conflicts means that you're currently overwriting new sprites that were added. To fix this, you need to update your branch to the latest version and then add the sprites. If you're unsure how this can be done:

In GitHub Desktop, go to your 'branch' tab
image

Click "Merge into Current Branch"
image

Near the bottom, select 'Upstream/master'
image

Click 'Create a merge commit' then commit it to your branch.

It will show you conflicting files, you should keep the files from upstream/master and not the ones from your branch. **Make a copy of your icons before you do this, or you will lose them.**

If it merges, then it'll show you:
image

**Comment by pisshole** [comment]
> Conflicts means that you're currently overwriting new sprites that were added. To fix this, you need to update your branch to the latest version and then add the sprites. If you're unsure how this can be done:
I already have updated multiple times, that's why my PR commits get half of them rewritten, since it automatically removes the conflicts (which has been done for this one last night)
It's just incredibly annoying to have to do this PR 3 times over. I'm not even doing anything wrong. Someone else's PR gets taken in before mine that affects these files for sprites and so mine get left at the curb. What am I supposed to do? Just keep bashing my head against this and re-adding them to the files then re-PRing and hoping this is the time my files get through first? I guess that's the only answer but it doesn't make it any more pleasant.

**Comment by pisshole** [comment]
I have to admit I'm a bit of an idiot as I just found you can re-push in your commits through the old PR... that's actually somewhat of a relief. It's still incredibly annoying but it makes the wait less grating.

**Pull request merged**
