### PR TITLE
Complete Armor Rework - PROPOSAL

### PR DESCRIPTION
**Pull request by SouthyOsmanli**
## About The Pull Request

This is the re-work I've wanted but ever faction feels the need constantly to buff armor because they get wiped the floor with by others - which creates this issue where one faction buffs, doesn't fix the other, and so on and so forth. 

We have craftable combat armor for factions to make the better armor their faction colors for usage that they can grab. This creates incentive to get better armor to use and make them the faction armors which are currently pointless besides the reinforced combat armor variant for your primes/troopers/initiates

This should end this stupid 'cold war' of buffing faction armors constantly and honestly 90% of the armors should **NOT** be changed past this besides probably a few balancing fixes as NCR armors are confusing due to how many people have their own snowflake armor and armors that do the exact same thing but have different descriptions and looks - which I do admit confuses me a bit as I don't play with/against NCR enough to learn what is what.

## Why It's Good For The Game

The faction armor cold-war fucks wasters, outlaws and others who wish to actually escalate, roleplay and in any-way stand a chance against factions with heavy armor. This should probably not be merged immediately as guns need to be reworked - mostly in terms of their damage and AP since some guns were balanced around this stupid cold war of armors we have going on.

## Changelog
:cl:
balance: Completely rebalances faction armor.
/:cl:

### CODE REVIEW

**Comment by OliOliOnsiPree** [comment]
👋 Hey. So my only concern here is that with the tribal nerf on armors, we barely have any upgrades on our armors yet. Which assuming in the tribal overhaul on armors however we shall? So like our max armor is tier V on heavy on default which no one gets it besides ours crafting menu. Which our upgraded set which can be made by everyone in a way is Deathclaw cloak as we are meant to be using tribal like items only. Which basically makes our armors only being an tier V at max. Which our heavy is only craftable and we cannot get it at the instantly start of the round, unless we legit rush the metal and or the doors in total with screwdrivers. Which absolutely is absolutely pretty much a bigger nerf on the tribals then anyone else.

**Comment by SouthyOsmanli** [comment]
> 👋 Hey. So my only concern here is that with the tribal nerf on armors, we barely have any upgrades on our armors yet. Which assuming in the tribal overhaul on armors however we shall? So like our max armor is tier V on heavy on default which no one gets it besides ours crafting menu. Which our upgraded set which can be made by everyone in a way is Deathclaw cloak as we are meant to be using tribal like items only. Which basically makes our armors only being an tier V at max. Which our heavy is only craftable and we cannot get it at the instantly start of the round, unless we legit rush the metal and or the doors in total with screwdrivers. Which absolutely is absolutely pretty much a bigger nerf on the tribals then anyone else.

If wanted I could either add another armor type as an in-between or I can probably give them a straight buff and make it tier 4 normal. I made it tier 3 since they're.. you know, tribals. And that's on-par with starting Waster gear. But I can possibly just make it so your heavy armor is tier 5 and make your normal  armor 4 - or just make an in-between for tier 4 and start you with 3. Also - I was under the assumption tribals used other armors they found rather than pure faction.

Either way, can easily fix it depending on which option is prefered.

**Comment by OliOliOnsiPree** [comment]
> > 👋 Hey. So my only concern here is that with the tribal nerf on armors, we barely have any upgrades on our armors yet. Which assuming in the tribal overhaul on armors however we shall? So like our max armor is tier V on heavy on default which no one gets it besides ours crafting menu. Which our upgraded set which can be made by everyone in a way is Deathclaw cloak as we are meant to be using tribal like items only. Which basically makes our armors only being an tier V at max. Which our heavy is only craftable and we cannot get it at the instantly start of the round, unless we legit rush the metal and or the doors in total with screwdrivers. Which absolutely is absolutely pretty much a bigger nerf on the tribals then anyone else.
> 
> If wanted I could either add another armor type as an in-between or I can probably give them a straight buff and make it tier 4 normal. I made it tier 3 since they're.. you know, tribals. And that's on-par with starting Waster gear. But I can possibly just make it so your heavy armor is tier 5 and make your normal armor 4 - or just make an in-between for tier 4 and start you with 3. Also - I was under the assumption tribals used other armors they found rather than pure faction.
> 
> Either way, can easily fix it depending on which option is prefered.

I would be down for a in-between, no one barely uses heavy armor due to its not the best sprite. Which from my understanding which will change in the overhaul for tribal armors. Which Chief will be getting there own armor sometime down the road. Since the chief comes with an level 7 helmet just not armor. Which I am more then fine with cooperating with that aswell. Those are just my two cents with nerfing tribal armors. Assuming you would want to nerf the three helmets for chief aswell as the Head hunters unique armor and helmet. Since it is tier 6 now and it only gets that armor and exclusive weapon to them. Also I understand tribals are a minor faction on the server and I am trying to be well reasonable to work with everyone who is trying to help 😄 Which I appreciate all of you.

**Comment by Lamasmaster** [comment]
So, only thing from me, corporal should keep mantle armor and troopers reinforced for simple fact that mantle is designation of NCOs for NCR of sorts otherwise looks fine to me.

**Comment by SouthyOsmanli** [comment]
I'm not working on this anymore so I'll do that change and either people can take the files and change it further or they can decide to merge them. I'm not working on this further.

**Pull request closed without merging**
