### PR TITLE
Scavvers of the Wasteland

### PR DESCRIPTION
**Pull request by AsterixCodix**
## About The Pull Request

Adds in a few items themed around scavengers in the wasteland (more to come).

Coming straight from FO:3/76 (stylised somewhere between the two games), the Auto Axe makes its' debut. Originating with The Pitt DLC for FO:3, alongside its weaker "parent", the Steel Saw, it's described as being a Steel Saw upgraded with car engine parts. As this was difficult to reflect in the sprite, the Steel Saw is slightly shorter and has a mostly grey/steel pallette, whilst the Auto Axe is longer and sports a more rusted yellow one. See:
image

Adds in 2 issues of SCAV! magazine to serve as skill books, to learn the crafting recipes for the items included here.

## Why It's Good For The Game

Adds a bit more flavour into the game and spices up melee combat a bit, all with the benefit of (mostly) fitting a single theme.

## Changelog
:cl:
add: Added Raider scavver outfit
add: Added female Raider scavver outfit
add: Added scavver outfit
add: Added female scavver outfit
add: Added the Auto Axe 
add: Added the Steel Saw
add: Added SCAV! Issue 1
add: Added SCAV! Issue 2
/:cl:

### CODE REVIEW

**Comment by AsterixCodix** [comment]
I _really_ didn't mean to mark this as "ready for review", I'm just trying to fix this so it can be merged.

**Comment by judgex** [comment]
Is this ready for merge?

**Comment by AsterixCodix** [comment]
> Is this ready for merge?

Will be once the checks have passed!

**Comment by AsterixCodix** [comment]
Ready to merge

**Pull request merged**
